### ISSUE TITLE
Fix CSS for alertToggler 

### ISSUE THREAD

**Issue by Xon** [Xon/XenForo2-AlertImprovements#5]
Bad css /less for discoverability;
```less
.alertToggler
{
	.alert &
	{
		opacity: 0;
	}

	.alert:hover &,
	.has-touchevents &
	{
		opacity: 1;
	}
}
```

Override with `.alert .alertToggler { opacity: 1; }`  via some custom CSS/LESS file to make this feature discoverable on a desktop enviroment.
